#!/usr/bin/env python3

from migen import *

from litex.build.openfpgaloader import OpenFPGALoader
from litex.build.generic_platform import Subsignal, Pins, IOStandard

from litex_boards.platforms import sitlinv_stlv7325_v1
from litex_boards.targets.sitlinv_stlv7325_v1 import _CRG

from litex.soc.integration.soc_core import SoCCore
from litex.soc.integration.builder import Builder

from liteeth.phy.gmii import LiteEthPHYGMIICRG

from litex.soc.cores.clock import S7PLL
from litex.gen import LiteXModule


"""
Clocks:
* MAC
    * input gtx_clk
        * gmii_phy_if main clock
        * generated on fpga, sent to MAC, MAC sends to PHY
    * input logic_clk
        * clock domain of external AXIS ports of FIFOs
        * use system clock
    * input gmii_rx_clk
        * generated by PHY from incoming data
    * input mii_tx_clk - actual GMII TX clock
        * 10/100 Mb clock generated by PHY
    * output gmii_tx_clk - actual GMII GTX clock
        * 1G: gtx_clk
        * 10/100: mii_tx_clk
"""


class _CRG(LiteXModule):
    def __init__(self, platform, sys_clk_freq):
        self.rst = Signal()
        self.cd_sys = ClockDomain()
        self.cd_gtx = ClockDomain()

        # Clk/Rst.
        clk200 = platform.request("clk200")
        # clk100 = platform.request("clk100")
        rst_n = platform.request("cpu_reset_n")

        # PLL.
        self.pll = pll = S7PLL(speedgrade=-2)
        self.comb += pll.reset.eq(~rst_n | self.rst)
        pll.register_clkin(clk200, 200e6)
        pll.create_clkout(self.cd_sys, sys_clk_freq)
        pll.create_clkout(self.cd_gtx, 125e6)
        # Ignore sys_clk to pll.clkin path created by SoC's rst.
        platform.add_false_path_constraints(self.cd_sys.clk, pll.clkin)


class EthernetTestbench(SoCCore):
    def __init__(
        self,
        platform,
        sys_clk_freq=200e6,
    ):
        SoCCore.__init__(
            self,
            platform,
            sys_clk_freq,
            cpu_type=None,
            integrated_sram_size=0,
            with_timer=False,
            with_uart=False,
        )

        self.platform = platform

        # Verilog sources
        platform.add_sources("../../gen", "EthernetTestbench.v")
        platform.add_sources("../../gen", "sources.v")

        # Ethernet 0 doesn't work due to io voltage conflict
        eth_num = 1
        eth_clocks = platform.request("eth_clocks", eth_num)
        eth_pads = platform.request("eth", eth_num)

        self.crg = _CRG(platform, sys_clk_freq)

        self.platform.add_period_constraint(self.crg.cd_gtx.clk, 1e9 / 125e6)
        self.platform.add_false_path_constraints(
            self.crg.cd_sys.clk, self.crg.cd_gtx.clk
        )
        self.platform.add_false_path_constraints(self.crg.cd_sys.clk, eth_clocks.rx)

        ios = {
            "i_clk": ClockSignal("sys"),
            "i_reset": ResetSignal("sys"),
            "i_io_gtx_clk": self.crg.cd_gtx.clk,
            "i_io_gtx_rst": ResetSignal("sys"),
            "i_io_gmii_gmii_rx_clk": eth_clocks.rx,
            "i_io_gmii_gmii_rxd": eth_pads.rx_data,
            "i_io_gmii_gmii_rx_dv": eth_pads.rx_dv,
            "i_io_gmii_gmii_rx_er": eth_pads.rx_er,
            # "i_io_gmii_mii_tx_clk": eth_clocks.tx,
            "o_io_gmii_gmii_tx_clk": eth_clocks.gtx,
            "o_io_gmii_gmii_txd": eth_pads.tx_data,
            "o_io_gmii_gmii_tx_en": eth_pads.tx_en,
            "o_io_gmii_gmii_tx_er": eth_pads.tx_er,
        }

        self.specials += Instance("EthernetTestbench", **ios)


def main():
    from litex.build.parser import LiteXArgumentParser

    platform = sitlinv_stlv7325_v1.Platform()

    parser = LiteXArgumentParser(
        platform=platform, description="LiteX SoC on AliExpress STLV7325 V1"
    )

    args = parser.parse_args()

    module = EthernetTestbench(platform=platform)

    builder = Builder(
        module,
        output_dir="build",
        compile_gateware=True,
    )

    if args.build:
        builder.build(**parser.toolchain_argdict)

    if args.load:
        prog = OpenFPGALoader(board="stlv7325", freq=3e6)
        prog.load_bitstream(builder.get_bitstream_filename(mode="sram"))


if __name__ == "__main__":
    main()
