name: Regression Tests

on: [push]

env:
  PY_VER: "3.10"

jobs:
  run_tests:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt

    - name: Set up Python $PY_VER
      uses: actions/setup-python@v2
      with:
        python-version: $PY_VER
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: ./hw/tb/run_all.sh
